package no.nav.hm.grunndata.db.legacy

import java.time.LocalDate

data class ProduktDTO(
    val adescshort: String?,
    val adraft: Boolean?,
    val aindate: String?,
    val aisapproved: Boolean?,
    val anbudid: String?,
    val aout: Boolean?,
    val aoutdate: String?,
    val apostdesc: String?,
    val apostid: String?,
    val apostnr: String?,
    val aposttitle: String?,
    val artid: String,
    val artname: String,
    val artno: String?,
    val artpostid: String?,
    val blobfileURL: String?,
    val blobfileURL_snet: String?,
    val blobtype: String?,
    val blobuse: String?,
    val hasanbud: Boolean?,
    val isactive: Boolean?,
    val isocode: String,
    val isotextshort: String?,
    val isotitle: String,
    val ldbid: String?,
    val newsexpire: LocalDate?,
    val newsid: String?,
    val newspublish: LocalDate?,
    val pisapproved: Boolean?,
    val postrank: Long?,
    val prodid: String,
    val prodname: String,
    val pshortdesc: String,
    val stockid: String?,
    val supplier: String?,
)
