version: '3'
services:
  postgresgrunndatadb:
    hostname: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/test/resources/postgres:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=none"]
  kafkagrunndata:
    hostname: kafkagrunndata
    image: confluentinc/cp-kafka:7.3.1
    logging:
      driver: none
    depends_on:
      - zookeepergrunndata
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeepergrunndata:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkagrunndata:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - grunndata-net
  zookeepergrunndata:
    image: confluentinc/cp-zookeeper:7.3.1
    hostname: zookeepergrunndata
    logging:
      driver: none
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - grunndata-net
  opensearchgrunndatadb:
    image: opensearchproject/opensearch:2.11.1
    hostname: opensearchgrunndatadb
    container_name: opensearchgrunndatadb
    ports:
      - 9200:9200
    environment:
      - cluster.name=gdb
      - node.name=opensearchgrunndatadb
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - grunndata-net
#  dashboardsgrunndatadb:
#    depends_on:
#      - opensearchgrunndatadb
#    image: opensearchproject/opensearch-dashboards:2.11.1
#    ports:
#      - 5601:5601
#    environment:
#      LOGGING_SILENT: "false"
#      OPENSEARCH_HOSTS: '["https://opensearchgrunndatadb:9200"]'
#    networks:
#      - opensearch-net
networks:
  grunndata-net:
