services:
  postgresdb:
    hostname: postgres
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/test/resources/postgres:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=none"]
  kafkadb:
    hostname: kafka
    image: confluentinc/cp-kafka:7.3.1
    logging:
      driver: none
    depends_on:
      - zookeeperdb
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - grunndata-net
  zookeeperdb:
    image: confluentinc/cp-zookeeper:7.3.1
    hostname: zookeeper
    logging:
      driver: none
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - grunndata-net
  opensearchdb:
    image: opensearchproject/opensearch:2.17.1
    hostname: opensearch
    ports:
      - 9200:9200
    environment:
      - cluster.name=gdb
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "_JAVA_OPTIONS=-XX:UseSVE=0"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=T3@mM1m3!"
    networks:
      - grunndata-net
  dashboardsdb:
    depends_on:
      - opensearchdb
    image: opensearchproject/opensearch-dashboards:2.17.1
    ports:
      - 5601:5601
    environment:
      LOGGING_SILENT: "false"
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - grunndata-net
networks:
  grunndata-net:
