apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-grunndata-db
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  port: 8888
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  env:
    - name: DB_DRIVER
      value: "org.postgresql.Driver"
    - name: HMDB_URL
      value: "http://hm-grunndata-hmdb2gdb"
    - name: RAPIDSANDRIVERS_ENABLED
      value: "{{ rapidsandrivers_enabled }}"
  gcp:
    sqlInstances:
      - name: hm-grunndata-db
        type: POSTGRES_14
        tier: {{ disk_tier }}
        diskType: SSD
        highAvailability: true
        diskSize: {{ disk_size }}
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: gdb
            envVarPrefix: DB
        cascadingDelete: false
  kafka:
    pool: {{ kafka_cluster }}
  leaderElection: true
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-hmdb2gdb
      external:
        - host: navikt.github.io
    inbound:
      rules:
        - application: hm-grunndata-index