ALTER TABLE index_item
    ALTER COLUMN created TYPE TIMESTAMP WITHOUT TIME ZONE
        USING created AT TIME ZONE 'Europe/Oslo',
    ALTER COLUMN updated TYPE TIMESTAMP WITHOUT TIME ZONE
        USING updated AT TIME ZONE 'Europe/Oslo';

ALTER TABLE index_item
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated SET DEFAULT CURRENT_TIMESTAMP;