micronaut:
  application:
    name: hm-grunndata-db
    thread-selection: auto
  executors:
    consumer:
      type: fixed
      nThreads: 1
  http:
    client:
      max-content-length: 100833718
      read-timeout: "15m"
  server:
    max-request-size: 100833718
    port: 8080
  caches:
    suppliers:
      charset: 'UTF-8'
    agreements:
      charset: 'UTF-8'
    agreementposts:
      charset: 'UTF-8'
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
datasources:
  default:
    url: ${DB_JDBC_URL:`jdbc:tc:postgresql:14:///gdb?TC_INITSCRIPT=file:src/test/resources/postgres/postgres-init.sql`}
    driverClassName: ${DB_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}
    username: ${DB_USERNAME:gdb}
    password: ${DB_PASSWORD:gdb}
    maximum-pool-size: 8
    minimum-idle: 0
    pool-name: default

flyway:
  datasources:
    default:
      locations: classpath:db
      clean-on-validation-error: true # only during dev and poc, will remove when we go to production.

opensearch:
  password: ${OPEN_SEARCH_PASSWORD:admin}
  user: ${OPEN_SEARCH_USERNAME:admin}
  url: ${OPEN_SEARCH_URI:`https://localhost:9200`}

hmdb:
  url: ${HMDB_URL:`http://localhost:8080`}