micronaut:
  application:
    name: hm-grunndata-db
    thread-selection: auto
  executors:
    consumer:
      type: fixed
      nThreads: 1
  http:
    client:
      max-content-length: 100833718
      read-timeout: "10m"
      event-loop-group: http
  netty:
    event-loops:
      http:
        num-threads: 10
        prefer-native-transport: true
  server:
    max-request-size: 100833718
    port: ${SERVER_PORT:8080}
  caches:
    suppliers:
      charset: 'UTF-8'
    agreements:
      charset: 'UTF-8'
  data:
    pageable:
      max-page-size: 2000
  metrics:
    enabled: true
    binders:
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
      jdbc:
        enabled: true
      kafka:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: false
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
datasources:
  default:
    url: ${DB_JDBC_URL:`jdbc:tc:postgresql:14:///gdb?TC_INITSCRIPT=file:src/test/resources/postgres/postgres-init.sql`}
    driverClassName: ${DB_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}
    username: ${DB_USERNAME:gdb}
    password: ${DB_PASSWORD:gdb}
    maximum-pool-size: 8
    minimum-idle: 0
    pool-name: default

flyway:
  datasources:
    default:
      locations: classpath:db

hmdb:
  url: ${HMDB_URL:`http://localhost:8081`}

# Rapids and rivers config
rapidsandrivers:
  enabled: ${RAPIDSANDRIVERS_ENABLED:false}
kafka:
  topic: teamdigihot.hm-grunndata-v1
  consumerGroupId: hm-grunndata-db-g1
  trustStorePath: ${KAFKA_TRUSTSTORE_PATH:}
  trustStorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  keystorePath: ${KAFKA_KEYSTORE_PATH:}
  keystorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  health:
    enabled: false

bestillingsordning:
  url: ${BESTILLINGSORDNING_URL:`https://navikt.github.io/digihot-sortiment/bestillingsordning_sortiment.json`}

schedulers:
  enabled: ${SCHEDULERS_ENABLED:false}

elector:
  path: ${ELECTOR_PATH:localhost}
