CREATE USER gdb with password 'gdb';
CREATE DATABASE gdb owner gdb;
CREATE USER register with password 'register';
CREATE DATABASE register owner register;
CREATE USER media with password 'media';
CREATE DATABASE media owner media;
CREATE USER importapi with password 'importapi';
CREATE DATABASE importapi owner importapi;
CREATE USER mediaproxy WITH password 'mediaproxy';
CREATE DATABASE mediaproxy owner mediaproxy;