name: deploy-direct
on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'What cluster?'
        required: true
        default: 'dev-gcp'
        type: choice
        options:
          - dev-gcp
          - prod-gcp
      version:
        description: 'What version?'
        required: true
        type: string
env:
  VERSION_TAG = ${{ inputs.version }}
  CLUSTER = ${{ inputs.cluster }}
jobs:
  deploy-direct:
    runs-on: ubuntu-latest
    environment: ${{ inputs.CLUSTER }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.VERSION_TAG }}
      - run: |
          echo "Cluster: $CLUSTER"
          echo "Version: $VERSION_TAG"
        
