name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
      - "docker-compose.yml"
    branches:
      - main

jobs:
  call-workflow:
    concurrency: deploy-dev
    permissions:
      contents: write
      id-token: write
      security-events: write
      actions: read
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v6
    with:
      NAIS_RESOURCE: ".nais/nais.yml"
      NAIS_VARS: ".nais/nais-dev.json"
      JAVA_VERSION: 17
      TEAM: "teamdigihot"
      CODEQL_ENABLED: true
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'main' }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

